# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://github.com/XijiaoLi/
title: Xijiao
email: xl2950@columbia.edu
author: Xijiao Li
description: > # "Xijiao's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: medium
    title: blog
    url: https://medium.com/@xijiaoli
  - icon: envelope-o
    title: email
    url: mailto:xl2950@columbia.edu
  - icon: github
    title: github
    url: https://github.com/XijiaoLi
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/xijiao-li/
  - icon: file-pdf-o
    title: resume
    url: https://www.linkedin.com/in/xijiao-li/
