# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Xijiao Li's Personal Page
email: xl2950@columbia.edu
author: Xijiao Li
description: Xijiao Li's Personal Page
